FROM node:latest

WORKDIR /app

COPY package-lock.json ./package-lock.json
COPY package.json ./package.json

RUN npm install

COPY controllers/ ./controllers/
COPY middleware/ ./middleware/
COPY models/ ./models/
COPY public/ ./public/
COPY routes/ ./routes/
COPY setup/ ./setup/
COPY util/ ./util/
COPY views/ ./views/
COPY .env.example ./.env.example
COPY index.js ./index.js

ENTRYPOINT [ "npm", "start" ]